### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by AhrimanSefid** [f4rber/BruteMiner#6]
C:\BruteMiner-main\BruteMiner-main>main.py -m 1
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Python310\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Python310\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Python310\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Python310\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Python310\lib\runpy.py", line 269, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Python310\lib\runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\BruteMiner-main\BruteMiner-main\main.py", line 36, in <module>
    m = Manager()
  File "C:\Python310\lib\multiprocessing\context.py", line 57, in Manager
    m.start()
  File "C:\Python310\lib\multiprocessing\managers.py", line 562, in start
    self._process.start()
  File "C:\Python310\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Python310\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Python310\lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Python310\lib\multiprocessing\spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "C:\Python310\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

**Comment by AhrimanSefid** [comment]
linux run ,can check awesome

![image](https://user-images.githubusercontent.com/1332246/148115559-1e825723-2655-407c-bfe4-511f4c878014.png)

**Comment by f4rber** [comment]
Script works only under linux distro.

**Comment by AhrimanSefid** [comment]
me try in windows 10 python 3.10.1 not work.
can fixed.
